services:
    frontend:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: frontend:latest
        ports:
            - '${APP_PORT:-8000}:80'
        networks:
            - frontend
        env_file:
            - .env
networks:
    frontend:
        driver: bridge
